# Generated by Django 3.2.20 on 2023-07-24 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('phoneNumber', models.CharField(max_length=10)),
                ('emailAddress', models.TextField(max_length=254)),
                ('birthday', models.DateField()),
                ('facebookLink', models.URLField()),
                ('twitterLink', models.URLField()),
                ('instagramLink', models.URLField()),
                ('notes', models.TextField(max_length=300)),
            ],
        ),
    ]
